FILES_INT   = module_interaction_specific_types.f90 module_interaction_specific.f90 \
              test_interaction.f90

SRC        += $(FILES_INT)
SRC_COPY   += $(addprefix $(INTSPECDIR)/vortex/, $(FILES_INT))

# compiler test for interaction kernels
TEST     = 0

ifeq ($(TEST), 1)
   CPPFLAGS_BACKEND = -DTEST_INTERACTION
endif
