#!/bin/bash -x
#MSUB -l nodes=8:ppn=4
#MSUB -l walltime=12:00:00
##MSUB -e ./
##MSUB -o ./
#MSUB -N pepc_test
#MSUB -M p.gibbon@fz-juelich.de
#MSUB -m e
### start of jobscript

### start of jobscript

###cd $WORKDIR
###echo "workdir: $WORKDIR"

# TASKS = nodes * ppn / tpt = 8 * 4 / 1 = 32
# NSLOTS = nodes * ppn = 128 * 8 = 1024
TASKS=4
echo "Executing $TASKS MPI tasks ..."
cp eqm.h run.h
mpiexec -np $TASKS ../bin/pepcb.juropa > pepc.out

