FILES_L   = pepc.f90 module_helper.f90

FILES_L_U = module_vtk_helpers.f90 \
            module_directsum.f90

SRC        += $(FILES_L)
SRC_COPY   += $(addprefix $(FRONTENDDIR)/pepc-essential/, $(FILES_L))

SRC        += $(FILES_L_U)
SRC_COPY   += $(addprefix $(UTILSDIR)/, $(FILES_L_U))

BACKENDTYPE = XYZQVM

#WALK = smpss
#WALK = pthreads_blocking
WALK = pthreads
