
# use Makefile.in if it exists, makefile.defs otherwise
ifneq ($(wildcard Makefile.in),)

include Makefile.in

else

include ../makefile.defs

MPICC:=$(CC)

# reset fancy CPPFLAGS of PEPC so that SL can use it for regular compiling with CC
CPPFLAGS:=

# defaults are set in the SL Makefile
#ECHO=echo
#MKDIR_P=mkdir -p

endif
