# Thanks to Jakob Fritz <j.fritz@fz-juelich.de> for the mkdocs skeleton.
---
site_name: Continuous Benchmarking for PEPC
docs_dir: mkdocs
site_dir: public
repo_url: https://gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc

theme:
  name: material
  custom_dir: mkdocs/custom_theme
  font: false
  logo: 'img/logo.png'
  favicon: 'img/icon.png'
  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top

nav:
  - 'Branch: master': master.ipynb
  - 'Branch: cb_testing': cb_testing.ipynb
  - 'Code Repository': 'https://gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc/'
  - 'Issue Tracker': 'https://gitlab.jsc.fz-juelich.de/SLPP/pepc/pepc/-/issues'

exclude_docs:

extra_css:
  - css/font.css
  - css/jupyter.css

plugins:
  - mkdocs-jupyter:
      execute: true
      include_requirejs: true
      include_source: true
      show_input: false
      no_input: true
      allow_errors: false

markdown_extensions:
  #  - admonition
  #  - pymdownx.highlight
  #  - attr_list

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra:
  generator: true
