#!/bin/sh
#
#  Script to produce PEPC tarball 
#  - resolves symbolic links and reports file sizes
#
if [ $# = 0 -o "$1" = "-h" -o "$1" = "-help" -o "$1" = "-?" ]; then
    echo "Call parameters: Version#"
    exit
fi

cd ..
VERSION=$1
rm -f pepc/pepc$VERSION.tar.gz
tar -vcf pepc/pepc$VERSION.tar --exclude-from=pepc/.excludes \
pepc/lpepcsrc \
pepc/pepc-b \
pepc/pepc-e \
pepc/tutorial \
pepc/demo_mixed \
pepc/doc \
pepc/tools \
pepc/makefiles.old \
pepc/bin/*_pes pepc/bin/*_dump pepc/bin/make_* pepc/bin/copy_* \
pepc/config.* \
pepc/acx* \
pepc/auto* \
pepc/README pepc/README.* pepc/DISCLAIMER pepc/TODO pepc/CHANGES \
gzip pepc/pepc$VERSION.tar
# Publish
cd pepc
#scp README jzam0403@jump:.
#scp pepc$VERSION.tar.gz jzam0403@jump:.

