FILES_L   = pepc.f90 module_helper.f90 module_variables.f90 fnpy.f90

FILES_L_U = module_vtk.f90 \
            module_base64.f90 \
            module_treediags.f90 \
            module_directsum.f90 \
            module_checkpoint.f90

LDLIBS += libnpy.a

SRC        += $(FILES_L)
SRC_COPY   += $(addprefix $(FRONTENDDIR)/pepc-numpy/, $(FILES_L))

SRC        += $(FILES_L_U)
SRC_COPY   += $(addprefix $(UTILSDIR)/, $(FILES_L_U))

BACKENDTYPE = XYZQVMB

#WALK = smpss
