#!/bin/sh

# Shell script to create new directories of
# PEs listed in PE_list

DATADIR=''
WFNAME=visdata


# ls wf_info.* |  sed -e 's/wf_info.//g' > ../timesteps
#cd $DATADIR

#
echo "List of PEs:"; cat PE_list
echo
cp PE_list PE_newlist

cat PE_list | while read PE
do
	eval ` \
	echo $PE | sed -e 's/pe//g' | \
 	awk '{ t = $1                 # Pe number
		s = 1000 + t + 16    # Add placeholder + increment
 		printf "NEWPE=pe%i3",s } ' | sed -e 's/1//' `
	if [ ! -d $NEWPE ]
	then
		echo "Creating $NEWPE"
		mkdir $NEWPE
		echo "$NEWPE" | cat >> PE_newlist
	else
  		echo "Directory" $NEWPE" already exists"
	fi

done
