
MYROOT = ../../../
include $(MYROOT)makefile.defs


FRONTENDNAME = pepcv
BACKEND      = vortex

# -------------------------------------------------------------------------------------------
# Source files
SOURCES.f90 =   physvars.f90 diagnostics.f90 module_remesh.f90 files.f90 setup.f90 special_start.f90 pusher.f90 stamp.f90 \
                cleanup.f90 pepc.f90 
SOURCES.UTILS.f90 = 
# -------------------------------------------------------------------------------------------

include $(MYROOT)$(FRONTENDDIR)makefile.frontend