FILES_V   = physvars.f90 files.f90 diagnostics.f90 manipulate_particles.f90 pepc.f90
FILES_V_U = module_vtk.f90 module_base64.f90

SRC        += $(FILES_V)
SRC_COPY   += $(addprefix $(FRONTENDDIR)/pepc-v/, $(FILES_V))

SRC        += $(FILES_V_U)
SRC_COPY   += $(addprefix $(UTILSDIR)/, $(FILES_V_U))

LDLIBS += libsl.a

include $(LPEPCDIR)/makefile.include
include $(PTHREADSDIR)/makefile.include
include $(INTSPECDIR)/vortex/makefile.include

