
MYROOT = ../../../
include $(MYROOT)makefile.defs


FRONTENDNAME = pepcv
BACKEND      = vortex

# -------------------------------------------------------------------------------------------
# Source files
SOURCES.f90 =   physvars.f90 files.f90 diagnostics.f90 manipulate_particles.f90 pepc.f90 
SOURCES.UTILS.f90 = module_vtk.f90 module_base64.f90
# -------------------------------------------------------------------------------------------

include $(MYROOT)$(FRONTENDDIR)makefile.frontend