
MYROOT = ../../../
include $(MYROOT)makefile.defs


FRONTENDNAME = pepcsph
BACKEND      = nearestneighbour

# -------------------------------------------------------------------------------------------
# Source files
SOURCES.f90 =   physvars.f90 files.f90 setup.f90 special_start.f90 stamp.f90 \
                cleanup.f90 pepc.f90 module_neighbour_test.f90 module_sph.f90
SOURCES.UTILS.f90 = 
# -------------------------------------------------------------------------------------------

include $(MYROOT)$(FRONTENDDIR)makefile.frontend