FILES_L   = pepc.f90 module_helper.f90

FILES_L_U = module_directsum.f90 

SRC        += $(FILES_L)
SRC_COPY   += $(addprefix $(FRONTENDDIR)/$(FRONTEND)/, $(FILES_L))

SRC        += $(FILES_L_U)
SRC_COPY   += $(addprefix $(UTILSDIR)/, $(FILES_L_U))

CPPFLAGS   += -DNO_SPATIAL_INTERACTION_CUTOFF

BACKENDTYPE = XYZQ

#WALK = pthreads_clustered
#WALK = simple
#WALK = openmp
WALK = pthreads
