# @job_name = kojak
# @job_type = parallel
# @wall_clock_limit = 00:25:00
# @notify_user = p.gibbon@fz-juelich.de
# @notification = complete
# @output = kojak_prefetch.out
# @error = err.$(jobid)
# @node = 1
# @total_tasks = 8
# @node_usage = not_shared 
# @resources = ConsumableCpus(1)
# @ initialdir = ~/tree/kojak
# @queue
module load kojak-2.1xl
export ELG_BLACKLIST=a.blist
export OMP_NUM_THREADS=1
cp kojak.h run.h
poe /home4/jzam04/jzam0401/tree/pepc/src_tune/pepc
expert a.elg
