# @job_name = kojak
# @job_type = parallel
# @wall_clock_limit = 00:25:00
# @notify_user = p.gibbon@fz-juelich.de
# @notification = complete
# @output = kojak_prefetch.out
# @error = err.$(jobid)
# @node = 1
# @total_tasks = 4
# @node_usage = shared 
# @resources = ConsumableCpus(1)
# @queue
module load kojak-2.2b2
export ELG_BLACKLIST=blist
export OMP_NUM_THREADS=1
cp kojak.h run.h
poe ../pepc-b/pepck
expert a.elg
