
FILES_INT   = module_interaction_specific.f90 \
              module_interaction_specific_types_XYZQVM.f90 \
              module_multipole.f90 \
              module_fmm_periodicity.f90

SRC        += $(FILES_INT)

FILES_INT  += multipole.h

SRC_COPY   += $(addprefix ./src/interaction_specific/log2d/, $(FILES_INT))
