MYROOT = ../../../
include $(MYROOT)makefile.defs


FRONTENDNAME = pepcs
BACKEND      = coulomb

# -------------------------------------------------------------------------------------------
# Source files
SOURCES.f90 =   physvars.f90 setup.f90 cleanup.f90 pepc-s.f90 main.f90
SOURCES.UTILS.f90 = 
# -------------------------------------------------------------------------------------------

include $(MYROOT)$(FRONTENDDIR)makefile.frontend