FILES_NN   = physvars.f90 files.f90 setup.f90 special_start.f90 stamp.f90 \
	     cleanup.f90 pepc.f90 module_neighbour_test.f90

FILES_NN_U = 
             
SRC        += $(FILES_NN)
SRC_COPY   += $(addprefix $(FRONTENDDIR)/$(FRONTEND)/, $(FILES_NN))

SRC        += $(FILES_NN_U)
SRC_COPY   += $(addprefix $(UTILSDIR)/, $(FILES_NN_U))

BACKEND = sph

