#include <stdlib.h>
#include <stdio.h>
#include <math.h>

void wichura2x64kernel( const double *p, const double mu, const double sigma, double *res );

/*
 * Test the implementation of the AS 241 algorithm by Wichura 1988.
 * 
 * The test reads uniformly distributed random variates generated by frand123
 * and compares the normally distributed random variates computed using the AS 241
 * algorithm to ones computed using the implementation provided by the GRASS GIS
 * project implemented in as241.c and stored in
 * tests/input_testWichura2x64Kernel.in
 */
int main()
{
   const size_t elements = 1000 * 1000 * 100;
   const double eps = 1e-14;
   FILE *funi, *fnorm;
   funi  = fopen( "tests/rand_double.out", "rb+" );
   fnorm = fopen( "tests/input_testWichura2x64Kernel.in", "rb+" );
   if( ( fnorm == NULL ) || ( funi == NULL ) )
   {
      perror( "Opening input files failed!" );
   }
   double uni[2], norm[2];
   int i;
   for( i = 0; i < elements; i += 2 )
   {
      if( ( fread( uni, sizeof(double), 2, funi ) != 2 ) || ( fread( norm, sizeof(double), 2, fnorm ) != 2 ) )
      {
         perror( "Reading input failed!" );
      }
      double res[ 2 ];
      //printf( "i = { %d, %d }\n", i, i+1 );
      wichura2x64kernel( uni, 0., 1., res );
      if( ( fabs( res[ 0 ] - norm[ 0 ] ) > eps ) || ( fabs( res[ 1 ] - norm[ 1 ] ) > eps ) )
      {
         printf( "Difference too large: i = { %d, %d }, uniform = { %e, %e }\n", i, i+1, uni[ 0 ], uni[ 1 ] );
         printf( "%d: res = %e, ref = %e, error = %e\n", i, res[ 0 ], norm[ 0 ], res[ 0 ] - norm[ 0 ] );
         printf( "%d: res = %e, ref = %e, error = %e\n", i+1, res[ 1 ], norm[ 1 ], res[ 1 ] - norm[ 1 ] );
         exit( 1 );
      }
   }
   return 0;
}
